### ISSUE TITLE
Bad Request Response

### ISSUE THREAD

**Issue by aasagba** [selfrefactor/proxyneedle#1]
Hi,

The package does not seem to work.

When running the example:

var proxyNeedle = require("proxyneedle")
proxyNeedle.action('http://www.bing.com/search?q=duckman',function(error, data){
    console.log(data)
})

I get undefined in Tonicdev.com and running it locally I get:

`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request - Invalid Header</h2>
<hr><p>HTTP Error 400. The request has an invalid header name.</p>
</BODY></HTML>`

Can you please confirm if the package does indeed work or if I have done something wrong?

Thanks,

Adrian.

**Comment by selfrefactor** [comment]
Hi,

I just see it. It was a fragile library, now it should work file.
