### ISSUE TITLE
TypeError: Cannot read property '0' of undefined. Proxy list down

### ISSUE THREAD

**Issue by davidynamic** [selfrefactor/proxyneedle#3]
> /home/ubuntu/app-info/node_modules/proxyneedle/index.js:14
>             arrProxy.push(data[i])
>                               ^
> 
> TypeError:  Cannot read property '0' of undefined
>     at /home/ubuntu/workspace/node_modules/proxyneedle/index.js:14:31

I'm getting this error because it seems like the list through which I get the proxies (var normalProxy = 'http://ilearnsmarter.com/proxy.json')  is down. Will you be putting it back up again or if not, can you tell me the structure of the JSON so I can create my own list? Also, are there any other parts of the code that are dependent on this site being up?

Thanks

**Comment by selfrefactor** [comment]
The new version doesn't rely on external JSON file, rather than it store the JSON itself. Please update to latest version and your issue should disappear.
